name: "Tests"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php-version: '5.6'
            phpunit-version: '5.7'
            symfony-version: '2.7.*'
          - php-version: '5.6'
            phpunit-version: '5.7'
            symfony-version: '2.8.*'
          - php-version: '5.6'
            phpunit-version: '5.7'
            symfony-version: '3.4.*'
          - php-version: '7.4'
            phpunit-version: '9.6'
            symfony-version: '4.4.*'
          - php-version: '7.4'
            phpunit-version: '9.6'
            symfony-version: '5.4.*'
          - php-version: '8.3'
            phpunit-version: '11.3'
            symfony-version: '6.4.*'
          - php-version: '8.3'
            phpunit-version: '11.3'
            symfony-version: '7.1.*'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "Install dependencies with composer"
        run: |
          composer require --no-update symfony/dependency-injection:${{ matrix.symfony-version }}
          composer require --no-update --dev phpunit/phpunit:${{ matrix.phpunit-version }}
          composer update --no-interaction --no-progress

      - name: "Run tests with phpunit/phpunit"
        run: vendor/bin/phpunit
